### ISSUE TITLE
Makefile hangs

### ISSUE THREAD

**Issue by fphilippe** [joe-akeem/contour-tiles#6] opened 2022-10-30 07:57 UTC
Hi,

frst of all, thank you for your great job. I've ran your image and it hangs with this error :

```
gdal_merge.py -o /data/tif/contour-4326.tif \
                                 /data/tif/srtm_34_02.tif \
                                 /data/tif/srtm_35_01.tif \
                                 /data/tif/srtm_35_02.tif \
                                 /data/tif/srtm_35_03.tif \
                                 /data/tif/srtm_35_04.tif \
                                 /data/tif/srtm_35_05.tif \
                                 /data/tif/srtm_36_01.tif \
                                 /data/tif/srtm_36_02.tif \
                                 /data/tif/srtm_36_03.tif \
                                 /data/tif/srtm_36_04.tif \
                                 /data/tif/srtm_36_05.tif \
                                 /data/tif/srtm_37_01.tif \
                                 /data/tif/srtm_37_02.tif \
                                 /data/tif/srtm_37_03.tif \
                                 /data/tif/srtm_37_04.tif \
                                 /data/tif/srtm_37_05.tif \
                                 /data/tif/srtm_38_01.tif \
                                 /data/tif/srtm_38_02.tif \
                                 /data/tif/srtm_38_03.tif \
                                 /data/tif/srtm_38_04.tif \
                                 /data/tif/srtm_38_05.tif \
                                 /data/tif/srtm_39_01.tif \
                                 /data/tif/srtm_39_02.tif \
                                 /data/tif/srtm_39_03.tif \
                                 /data/tif/srtm_39_04.tif \
                                 /data/tif/srtm_39_05.tif \
                                 /data/tif/srtm_40_01.tif \
                                 /data/tif/srtm_40_02.tif \
                                 /data/tif/srtm_40_03.tif \
                                 /data/tif/srtm_40_04.tif \
                                 /data/tif/srtm_40_05.tif
0...10...20...30...40...50...60...70...80...90...100 - done.
free(): invalid pointer
make: *** [Makefile:133: /data/tif/contour-4326.tif] Aborted (core dumped)
make: *** Deleting file '/data/tif/contour-4326.tif'
```

Crawling the web, i found this issue : [GDAL/ogr2ogr/ogrinfo produces an invalid pointer error each time I run it](https://stackoverflow.com/questions/72345761/gdal-ogr2ogr-ogrinfo-produces-an-invalid-pointer-error-each-time-i-run-it).

What do you think about that ?

Regards,

Fabien

**Comment by joe-akeem** [comment] 2022-10-31 08:44
Hi, not sure at all what to make of this. I can't even reproduce this one because I now keep bumping into issue #4 myself. Not sure where that one came from either nor how to fix it, the image worked for me at some point. TBH I currently can't find much time to look into these issues but am happy to consider any PRs that address the problems. Since in the issue description you posted above, there seems to be a reference to ubuntu: have you tried changing the parent image from  `osgeo/gdal:ubuntu-full-3.5.2` to e.g. `osgeo/gdal:alpine-small-3.5.3`? That should also reduce the image size.

**Comment by fphilippe** [comment] 2022-10-31 10:55
Hi, i found the solution, just for this problem !

As explained in the following link [GDAL/ogr2ogr/ogrinfo produces an invalid pointer error each time I run it](https://stackoverflow.com/questions/72345761/gdal-ogr2ogr-ogrinfo-produces-an-invalid-pointer-error-each-time-i-run-it), it seems to be a linking error. The solution is given at the following link : [[gdal-dev] how to completely remove gdal from Ubuntu 20.04 and install from scratch](https://lists.osgeo.org/pipermail/gdal-dev/2020-September/052711.html).

For me, it not works totally fine with the last version of ubuntu full, `osgeo/gdal:ubuntu-full-3.5.2`. I've just added, in the Dockerfile, `RUN apt-get remove -y libproj.so.15` after `RUN apt-get update -y && ...`.

I've tested the image and let it go to the end, to verify that everything gonna be alright ! And everything didn't gone to be alright. I've then bumped onto the [Hit 2G/4G file limit](https://github.com/joe-akeem/contour-tiles/issues/4)...

I'll try to investigate...

Regards,

Fabien

**Comment by joe-akeem** [comment] 2022-11-01 11:59
`osgeo/gdal:ubuntu-full-3.5.2` is not the latest, `osgeo/gdal:ubuntu-full-3.5.3` is 🤔  It doesn't contain `libproj.so.15` any more. I f that solves the problem too then I'd rather update to that version rather than remove the lib.
Since I can't reproduce the problem that you encountered, @fphilippe : would you mind trying PR https://github.com/joe-akeem/contour-tiles/pull/7 ? If it works for you, I'll merge that, otherwise we'll add `RUN apt-get remove -y libproj.so.15` to the `Dockerfile`.

**Comment by joe-akeem** [comment] 2022-11-01 13:59
Strangely enough, I suddenly now also got this error while trying to make progress with https://github.com/joe-akeem/contour-tiles/issues/4. The update to `osgeo/gdal:ubuntu-full-3.5.3` alone didn't fix the problem so I added the removal of `libproj15` and it seems to work now. Will merge the PR and close this issue. Thanks for your input, @fphilippe! Hope this works for you too.

**Closed** 2022-11-01 14:00 UTC
